services:
  - type: web
    name: tfxonu
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/tfxonuu/Botfather
    branch: https://github.com/tfxonuu
    autoDeploy: false
    envVars:
      - key: 8033732232:AAF_W5lgzZhFjTEZJ0qnMTxtnFqqUZTBuEo
        sync: false
      - key: 27293287
        sync: false
      - key: 052041b03a7028b3bd11da3143cffa0e
        sync: false
      - key: 7533484450
        sync: false
      - key: SHAHNAWAZ
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
